spring.application.name=resourceServer

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

server.port=8081
spring.config.import=optional:file:.env[.properties]

logging.level.root=INFO

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE